version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  monolith:
    image: microservices-loves-cqrs/monolith
    container_name: monolith
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Dspring.cloud.stream.kafka.binder.zkNodes=zookeeper -Dspring.cloud.stream.kafka.binder.brokers=kafka"
    depends_on:
      - kafka

  web:
    image: microservices-loves-cqrs/web
    container_name: web
    expose:
      - "80"
    external_links:
      - monolith:api
    ports:
      - 8081:80