version: '2'
services:

  monolith:
    image: microservices-loves-cqrs/monolith
    container_name: monolith
    expose:
      - "8080"
    ports:
      - 8080:8080

  web:
    image: microservices-loves-cqrs/web
    container_name: web
    expose:
      - "80"
    external_links:
      - monolith:api
    ports:
      - 8081:80
