databaseChangeLog:
  - changeSet:
      id: 1
      author: malvarez
      changes:
        - createTable:
            tableName: inventory
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: product
                  type: uuid
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: available
                  type: bigint
                  constraints:
                    nullable: false